### ISSUE TITLE
View 3D point cloud on RVIZ

### ISSUE THREAD

**Issue by chapa17** [studennis911988/dso_ros_rviz#1]
Hello,

Thank you for your modification in DSO_ROS. I need to visualize 3D point cloud on RVIZ but it isn't a live camera stream. Does this implementation work on TUM dataset?

**Comment by studennis911988** [comment]
Hi, chapa.
The current implementation of 3D point cloud in myOutputWrapper fires when a frame and the mappoints it saw were marginalized.
All you have to do is take the data member std::vector<Eigen::Vector3d> and convert to RVIZ acceptable format.

If you need more detailed implementation of RVIZ format part, I may upload the files.

BR,
Dennis

**Comment by chapa17** [comment]
It would be a great help if you already have it implemented, since I am new to ROS. 

I am also stuck with the understanding that in order to run DSO on my own dataset and view the results on RVIZ I do not need to run dso_ros code files, correct? 

Thanks!
